Initial port of RabbitMQ image elements
* Installs rabbitmq-server
* Templatized vesions of rabbitmq.config and erlang.cookie
* Modify devstack scripts to build Cue Image

Change-Id: I57ac73aaff0c936f3b4f1d63de0cf19266df8b1c

diff --git a/contrib/devstack/lib/cue b/contrib/devstack/lib/cue
--- a/contrib/devstack/lib/cue
+++ b/contrib/devstack/lib/cue
@@ -51,7 +51,7 @@ CUE_SERVICE_PORT=${CUE_SERVICE_PORT:-8795}
 CUE_MANAGEMENT_KEY='cue-mgmt-key'
 CUE_RABBIT_SECURITY_GROUP='cue-rabbitmq'
 
-UBUNTU_IMAGE_NAME='ubuntu-14.04-server'
+UBUNTU_IMAGE_NAME='cue-rabbitmq'
 UBUNTU_IMAGE_URL='https://cloud-images.ubuntu.com/releases/14.04/release-20150305/ubuntu-14.04-server-cloudimg-amd64-disk1.img'
 UBUNTU_IMAGE_MD5='00662c59ca52558e7a3bb9a67d194730'
 UBUNTU_IMAGE_MINDISK=4
@@ -59,6 +59,10 @@ UBUNTU_IMAGE_MINDISK=4
 CUE_FLAVOR=cue.small
 CUE_FLAVOR_PARAMS="--id 8795 --ram 512 --disk $UBUNTU_IMAGE_MINDISK --vcpus 1"
 CUE_RABBIT_SECURITY_GROUP='cue-rabbitmq'
+
+CUE_RABBIT_IMAGE_ELEMENTS=${CUE_RABBIT_IMAGE_ELEMENTS:-\
+vm ubuntu os-refresh-config os-apply-config ntp hosts \
+cue-rabbitmq-base}
 
 # cleanup_cue - Remove residual data files, anything left over from previous
 # runs that a clean run would need to clean up
@@ -176,27 +180,11 @@ function init_cue {
         cue-manage --config-file $CUE_CONF taskflow upgrade
     fi
 
-    # Download ubuntu image to devstack/files
-    if [[ ! -f $TOP_DIR/files/${UBUNTU_IMAGE_NAME}.img ]]; then
-        curl -o $TOP_DIR/files/${UBUNTU_IMAGE_NAME}.img -L $UBUNTU_IMAGE_URL
-    fi
-
     OPENSTACK_CMD="openstack --os-token $TOKEN"
-    # Load ubuntu image to glance if one does not exist
-    if [[ -z $($OPENSTACK_CMD image list | grep $UBUNTU_IMAGE_NAME) ]]; then
-        $OPENSTACK_CMD image create --disk-format qcow2 --container-format bare --min-disk $UBUNTU_IMAGE_MINDISK --file $TOP_DIR/files/${UBUNTU_IMAGE_NAME}.img --checksum $UBUNTU_IMAGE_MD5 --public $UBUNTU_IMAGE_NAME
-    fi
 
     # Create cue specific flavor if one does not exist
     if [[ -z $($OPENSTACK_CMD flavor list | grep $CUE_FLAVOR) ]]; then
         $OPENSTACK_CMD flavor create $CUE_FLAVOR_PARAMS $CUE_FLAVOR
-    fi
-
-    # Set os_image_id
-    # TODO(sputnik13): this is a workaround until "image selector" is complete
-    UBUNTU_IMAGE_ID=$($OPENSTACK_CMD image list | grep $UBUNTU_IMAGE_NAME | tr -d ' ' | cut -f 2 -d '|')
-    if [ "$UBUNTU_IMAGE_ID" ]; then
-        iniset $CUE_CONF api os_image_id $UBUNTU_IMAGE_ID
     fi
 
     # Set os_security_group
@@ -214,6 +202,8 @@ function init_cue {
     if [ $CUE_MANAGEMENT_KEY ]; then
         iniset $CUE_CONF openstack os_key_name $CUE_MANAGEMENT_KEY
     fi
+
+    build_cue_rabbit_test_image
 }
 
 # install_cue - Collect source and prepare
@@ -252,6 +242,30 @@ function stop_cue {
     # Kill the cue screen windows
     stop_process cue-api
 }
+
+# build_cue_rabbit_test_image() - Build and upload functional test image
+function build_cue_rabbit_test_image {
+    if is_service_enabled dib; then
+        local image_name=cue-rabbitmq-test-image
+
+        # Elements path for tripleo-image-elements and cue-image-elements
+        local elements_path=$TIE_DIR/elements:$CUE_DIR/contrib/image-elements
+
+        disk_image_create_upload "$image_name" "$CUE_RABBIT_IMAGE_ELEMENTS" "$elements_path"
+
+        # Set os_image_id
+        # TODO(sputnik13): this is a workaround until "image selector" is complete
+        UBUNTU_IMAGE_ID=$($OPENSTACK_CMD image list | grep $image_name | tr -d ' ' | cut -f 2 -d '|')
+        if [ "$UBUNTU_IMAGE_ID" ]; then
+            iniset $CUE_CONF api os_image_id $UBUNTU_IMAGE_ID
+        fi
+    else
+        echo "Error, Builing RabbitMQ Image requires dib" >&2
+        echo "Add \"enable_service dib\" to your localrc" >&2
+        exit 1
+    fi
+}
+
 
 # Restore xtrace
 $XTRACE
